# Generated by Django 3.1.5 on 2021-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20210113_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full_time', 'Full time'), ('Part_time', 'Part time')], max_length=15),
        ),
    ]
