# Generated by Django 3.1.5 on 2021-01-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20210114_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
